### ISSUE TITLE
Stripe Customer retrieve: Support ?expand=default_source query parameter value

### ISSUE THREAD

**Issue by M0dM** [adrienverge/localstripe#32]
I am using dj-stripe for retrieving stripe webhooks to populate my database and localstripe to test the features I am using in dj-stripe and the code I've implemented above it.

dj-stripe use expand=default_source query parameter to retrieve expanded default_source values for Customer instances. (Line reference in dj-stripe source code : https://github.com/dj-stripe/dj-stripe/blob/1.2.3/djstripe/models.py#L790)

I would appreciate very much to be have this expand value supported in localstripe.

I can propose something like I've done earlier in a PR but I think we may find a way to do this more globally to support other fields expansion.

Please find bellow more documentation about expanded objects:

Stripe reference about expanded objects :
* https://stripe.com/docs/api/expanding_objects

Similar issues in fake_stripe and stripe-ruby-mock:
* https://github.com/thoughtbot/fake_stripe/issues/85
* https://github.com/rebelidealist/stripe-ruby-mock/issues/109

Some tests I've made : 
```bash
 benoit@benoit:~/Svn/WebProducts/Dxf2Dxf$ curl -X POST 127.0.0.1:8420/v1/customers -d email=dummy@email.fr  -u sk_test_12345:
{
  "account_balance": 0,
  "business_vat_id": null,
  "created": 1544111246,
  "currency": "eur",
  "default_source": null,
  "delinquent": false,
  "description": "",
  "discount": null,
  "email": "dummy@email.fr",
  "id": "cus_QcVgMB5sojJfvU",
  "livemode": false,
  "metadata": {},
  "object": "customer",
  "shipping": null,
  "sources": {
    "data": [],
    "has_more": false,
    "object": "list",
    "total_count": 0,
    "url": "/v1/customers/cus_QcVgMB5sojJfvU/sources"
  },
  "subscriptions": {
    "data": [],
    "has_more": false,
    "object": "list",
    "total_count": 0,
    "url": "/v1/customers/cus_QcVgMB5sojJfvU/subscriptions"
  }
}
benoit@benoit:~/Svn/WebProducts/Dxf2Dxf$ curl 127.0.0.1:8420/v1/customers/cus_QcVgMB5sojJfvU -u sk_test_12345:
{
  "account_balance": 0,
  "business_vat_id": null,
  "created": 1544111246,
  "currency": "eur",
  "default_source": null,
  "delinquent": false,
  "description": "",
  "discount": null,
  "email": "dummy@email.fr",
  "id": "cus_QcVgMB5sojJfvU",
  "livemode": false,
  "metadata": {},
  "object": "customer",
  "shipping": null,
  "sources": {
    "data": [],
    "has_more": false,
    "object": "list",
    "total_count": 0,
    "url": "/v1/customers/cus_QcVgMB5sojJfvU/sources"
  },
  "subscriptions": {
    "data": [],
    "has_more": false,
    "object": "list",
    "total_count": 0,
    "url": "/v1/customers/cus_QcVgMB5sojJfvU/subscriptions"
  }
}
 benoit@benoit:~/Svn/WebProducts/Dxf2Dxf$ curl 127.0.0.1:8420/v1/customers/cus_QcVgMB5sojJfvU?expand=default_source -u sk_test_12345:
{
  "error": {
    "message": "Bad request",
    "type": "invalid_request_error"
  }
}
 benoit@benoit:~/Svn/WebProducts/Dxf2Dxf$ curl 127.0.0.1:8420/v1/customers/cus_QcVgMB5sojJfvU?expand[]=default_source -u sk_test_12345:
<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
```
```bash
::ffff:127.0.0.1 [06/Dec/2018:15:47:26 +0000] "POST /v1/customers HTTP/1.1" 200 816 "-" "curl/7.62.0"
::ffff:127.0.0.1 [06/Dec/2018:15:48:30 +0000] "GET /v1/customers/cus_QcVgMB5sojJfvU HTTP/1.1" 200 816 "-" "curl/7.62.0"
::ffff:127.0.0.1 [06/Dec/2018:15:48:43 +0000] "GET /v1/customers/cus_QcVgMB5sojJfvU?expand=default_source HTTP/1.1" 400 253 "-" "curl/7.62.0"
Traceback (most recent call last):
  File "/home/benoit/.local/share/virtualenvs/dxf_authz/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/benoit/.local/share/virtualenvs/dxf_authz/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/home/benoit/.local/share/virtualenvs/dxf_authz/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/home/benoit/Git/localstripe/localstripe/server.py", line 55, in error_middleware
    return await handler(request)
  File "/home/benoit/Git/localstripe/localstripe/server.py", line 185, in auth_middleware
    return await handler(request)
  File "/home/benoit/.local/share/virtualenvs/dxf_authz/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 118, in handler_wrapper
    result = old_handler(*args, **kwargs)
  File "/home/benoit/Git/localstripe/localstripe/server.py", line 206, in f
    return json_response(cls._api_retrieve(id)._export(expand=expand))
  File "/home/benoit/Git/localstripe/localstripe/resources.py", line 213, in _export
    do_expand(path, obj)
  File "/home/benoit/Git/localstripe/localstripe/resources.py", line 206, in do_expand
    assert type(id) is str
AssertionError
::ffff:127.0.0.1 [06/Dec/2018:15:59:38 +0000] "GET /v1/customers/cus_QcVgMB5sojJfvU?expand%5B%5D=default_source HTTP/1.1" 500 330 "-" "curl/7.62.0"
```

**Comment by adrienverge** [comment]
Hey Benoit, doesn't this already work?
I've created https://github.com/adrienverge/localstripe/pull/33 to show an example. Does it do the job for you?

**Comment by M0dM** [comment]
Yes, you're right.
Has I've commented in #33, stripe legacy api raises an InvalidRequestError while trying to expand default_source on a Customer without any source registered.

**Comment by adrienverge** [comment]
See https://github.com/adrienverge/localstripe/pull/46.
