### ISSUE TITLE
Is localstripe compatible with official stripe libraries?

### ISSUE THREAD

**Issue by kerak19** [adrienverge/localstripe#7]
I'm using stripe-go for communication with stripe and i've tried to request create of customer.

For example, when i set business vat id in customer object:

```
172.17.0.1 [20/Mar/2018:08:22:29 +0000] "POST /v1/customers/cus_CVGDyDxiOKdQXu/cards HTTP/1.1" 404 172 "-" "Stripe/v1 GoBindings/29.3.0"                                                                           
Error handling request                                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/local/lib/python3.6/site-packages/aiohttp-3.0.9-py3.6.egg/aiohttp/web_protocol.py", line 381, in start                                                                                                
    resp = await self._request_handler(request)                                                                                                                                                                    
  File "/usr/local/lib/python3.6/site-packages/aiohttp-3.0.9-py3.6.egg/aiohttp/web_app.py", line 310, in _handle                                                                                                   
    resp = await handler(request)                                                                                                                                                                                  
  File "/usr/local/lib/python3.6/site-packages/aiohttp-3.0.9-py3.6.egg/aiohttp/web_middlewares.py", line 88, in impl                                                                                               
    return await handler(request)                                                                                                                                                                                  
  File "/usr/local/lib/python3.6/site-packages/localstripe-1.0.0-py3.6.egg/localstripe/server.py", line 52, in error_middleware                                                                                    
    return await handler(request)                                                                                                                                                                                  
  File "/usr/local/lib/python3.6/site-packages/localstripe-1.0.0-py3.6.egg/localstripe/server.py", line 159, in auth_middleware                                                                                    
    return await handler(request)                                                                                                                                                                                  
  File "/usr/local/lib/python3.6/site-packages/localstripe-1.0.0-py3.6.egg/localstripe/server.py", line 171, in f                                                                                                  
    return json_response(cls._api_create(**data)._export())                                                                                                                                                        
  File "/usr/local/lib/python3.6/site-packages/localstripe-1.0.0-py3.6.egg/localstripe/resources.py", line 109, in _api_create                                                                                     
    return cls(**data)                                                    
TypeError: __init__() got an unexpected keyword argument 'business_vat_id'                                               
```
Creating customer success when i've deleted business vat id.

Also i have problem while creating credit card:

```
2018/03/20 09:30:06 Requesting POST localhost:8420/v1/customers/cus_M4gs2trz3fIwGV/cards
2018-03-20T09:30:06.871+0100    ERROR   payments/create_card.go:88      stripe create card error        {"email": "lo+1@idesign.center", "error": "invalid character ':' after top-level value"}
2018/03/20 09:31:22 Unsolicited response received on idle HTTP channel starting with "\r\n"; err=<nil>
```
Where card token is "tok_amex" and customer_id is one i got from localstripe.

**Comment by adrienverge** [comment]
Hi, thanks for the feedback!

I've just pushed localstripe 1.0.1 that should solve the `business_vat_id` problem.

About the `/v1/customers/cus_M4gs2trz3fIwGV/cards` error, it happens because this route doesn't exist. Isn't the correct route named `/v1/customers/cus_M4gs2trz3fIwGV/sources`? At least that is what is written in [Stripe docs](https://stripe.com/docs/api/curl#create_card).
Could you try with `/sources` instead of `/cards`?

**Comment by kerak19** [comment]
Unfortunately path to cards(sources) isn't set by me but by stripe-go. Looks like stripe-go is a little behind current API version and soon it will be updated.

Thanks for quick change for `business_vat_id`.

**Comment by adrienverge** [comment]
OK, got it.

Could you try changing [this line](https://github.com/adrienverge/localstripe/blob/81ccb7b4ddb2ec10f482959e573b71524db98d0f/localstripe/resources.py#L415) to use `/cards` (instead of `/sources`), and see if this works?
(the file could be at `~/.local/lib/python3.6/site-packages/localstripe/resources.py` or `/usr/lib*/python3*/site-packages/localstripe/resources.py`, depending on where you installed localstripe)

If it works, we can include a "compatibility fix" in localstripe.

**Comment by kerak19** [comment]
Hey, i'll probably try this tomorrow. Thanks

**Comment by adrienverge** [comment]
Thanks for the feedback. I've added the `/cards` legacy route, so that you can use it.
See localstripe 1.1.1.
